---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-metricbeat
      metricbeat_elasticsearch_password: "My-P@s5w0rd."
      metricbeat_modules:
        - name: system
          state: enabled
